package com.lik.android.main;

public class UploadObject {
	String PHFL_CMPY_ID;
	String PHFL_PHOTOFILE_ID;
	String PHFL_NAME;
	String PHFL_PATH;
	String PHFL_DATE;
	String PHFL_LONGITUDE;
	String PHFL_LATITUDE;
	String PHFL_PROJECT_ID;
	String PHFL_CUST_ID;
	String PHFL_SALES_ID;
	String PHFL_PHOTOSTATE_ID;
	String PHFL_REMARK;
	String PHFL_POSITION_DIFFERENCE;
	String PHFL_GRADE;
	
	public UploadObject(String PHFL_CMPY_ID,String PHFL_PHOTOFILE_ID,String PHFL_NAME,String PHFL_PATH,String PHFL_DATE,String PHFL_LONGITUDE,
			String PHFL_LATITUDE,String PHFL_PROJECT_ID,String PHFL_CUST_ID,String PHFL_SALES_ID,String PHFL_PHOTOSTATE_ID,String PHFL_REMARK,
			String PHFL_POSITION_DIFFERENCE,String PHFL_GRADE){
		this.PHFL_CMPY_ID=PHFL_CMPY_ID;
		this.PHFL_PHOTOFILE_ID=PHFL_PHOTOFILE_ID;
		this.PHFL_NAME=PHFL_NAME;
		this.PHFL_PATH=PHFL_PATH;
		this.PHFL_DATE=PHFL_DATE;
		this.PHFL_LONGITUDE=PHFL_LONGITUDE;
		this.PHFL_LATITUDE=PHFL_LATITUDE;
		this.PHFL_PROJECT_ID=PHFL_PROJECT_ID;
		this.PHFL_CUST_ID=PHFL_CUST_ID;
		this.PHFL_SALES_ID=PHFL_SALES_ID;
		this.PHFL_PHOTOSTATE_ID=PHFL_PHOTOSTATE_ID;
		this.PHFL_REMARK=PHFL_REMARK;
		this.PHFL_POSITION_DIFFERENCE=PHFL_POSITION_DIFFERENCE;
		this.PHFL_GRADE=PHFL_GRADE;
		
	}
}
